[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py seed_demo && gunicorn flowershop.wsgi --log-file -"
healthcheckPath = "/api/shops/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3