"""
Django settings for flowershop project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Auto-load .env file if present (development convenience).
# In production (Railway) env vars are set by the platform.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# ---------------------------------------------------------------------------
# Shop config — single-tenant deployment.
# Edit these in .env to customise YOUR shop.
# ---------------------------------------------------------------------------
SHOP_NAME = os.environ.get('SHOP_NAME', 'Floral')
SHOP_SLUG = os.environ.get('SHOP_SLUG', 'flowery')
SHOP_ADDRESS = os.environ.get('SHOP_ADDRESS', '')
SHOP_PHONE = os.environ.get('SHOP_PHONE', '')
SHOP_EMAIL = os.environ.get('SHOP_EMAIL', '')


# ---------------------------------------------------------------------------
# Core security settings — read from env vars on Railway
# ---------------------------------------------------------------------------
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-kx#5t1s-ax+41629by2b4-!y2cn#($tn%3nipnuug-8w06mc%f',
)

DEBUG = os.environ.get('DEBUG', '1') == '1'

# Comma-separated list, e.g. "myapp.up.railway.app,localhost,127.0.0.1"
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,.railway.app',
).split(',')

# Trust HTTPS forwarded by Railway's proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF: trust Railway's HTTPS domains
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://*.railway.app,https://*.up.railway.app',
    ).split(',')
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'cloudinary',
    'cloudinary_storage',

    # Local apps
    'accounts.apps.AccountsConfig',
    'catalog',
    'orders',
]

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# ---------------------------------------------------------------------------
# Signup codes (set on Railway as environment variables)
# These codes let staff register as Manager/Worker. Customers don't need a code.
# ---------------------------------------------------------------------------
MANAGER_SIGNUP_CODE = os.environ.get('MANAGER_SIGNUP_CODE', 'CHANGE_ME_MANAGER')
WORKER_SIGNUP_CODE = os.environ.get('WORKER_SIGNUP_CODE', 'CHANGE_ME_WORKER')

# ---------------------------------------------------------------------------
# Encryption key for sensitive DB fields (Sberbank passwords, Telegram tokens, etc.)
# Generate once with:  python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Store on Railway as FIELD_ENCRYPTION_KEY. NEVER commit this.
# ---------------------------------------------------------------------------
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

# ---------------------------------------------------------------------------
# Sberbank — platform-level fallback only.
# Each shop configures its own credentials in the dashboard
# (see accounts.ShopPaymentSettings). These values are ONLY used when a shop
# hasn't configured its own — useful for demos and a single-tenant deploy.
# ---------------------------------------------------------------------------
SBERBANK_FALLBACK_USERNAME = os.environ.get('SBERBANK_FALLBACK_USERNAME', '')
SBERBANK_FALLBACK_PASSWORD = os.environ.get('SBERBANK_FALLBACK_PASSWORD', '')
SBERBANK_FALLBACK_RETURN_URL = os.environ.get(
    'SBERBANK_FALLBACK_RETURN_URL', 'http://localhost:8000/orders/return/'
)
SBERBANK_FALLBACK_FAIL_URL = os.environ.get(
    'SBERBANK_FALLBACK_FAIL_URL', 'http://localhost:8000/orders/fail/'
)

# ---------------------------------------------------------------------------
# Media storage
#   - USE_CLOUDINARY=1     → Cloudinary (recommended for production)
#   - USE_S3_STORAGE=1     → Railway/S3 bucket (alternative)
#   - neither set          → local /media (dev only — files vanish on Railway redeploy)
# ---------------------------------------------------------------------------
USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', '').lower() in ('1', 'true', 'yes')
USE_S3_STORAGE = os.environ.get('USE_S3_STORAGE', '').lower() in ('1', 'true', 'yes')

# Default media URL (overridden below if using cloud storage)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default storage backends — modified below depending on USE_CLOUDINARY / USE_S3_STORAGE
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
        'SECURE': True,
    }
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }
elif USE_S3_STORAGE:
    INSTALLED_APPS += ['storages']

    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_ADDRESSING_STYLE = 'virtual'

    STORAGES['default'] = {
        'BACKEND': 'flowershop.storage_backends.PublicMediaStorage',
    }

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    else:
        MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# DRF
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flowershop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flowershop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL env var if set (Railway Postgres), else SQLite for local dev.

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------------------------------------------------------
# Frontend: React build output is served as static files.
# `npm run build` writes to /static_frontend/. Django finds it via STATICFILES_DIRS.
# In production, run `python manage.py collectstatic` to gather everything.
# ---------------------------------------------------------------------------
STATICFILES_DIRS = [
    BASE_DIR / 'static_frontend',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves compressed static files in production.
# Override only the staticfiles backend, leave default (media) alone.
STORAGES['staticfiles'] = {
    'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
}

# Tell WhiteNoise where to look for index.html and assets/
WHITENOISE_ROOT = BASE_DIR / 'static_frontend'