# Generated by Django 5.2.13 on 2026-05-02 18:29

import accounts.shop_settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='User-friendly name, e.g. "Home", "Office".', max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('address_line', models.CharField(max_length=500)),
                ('apartment', models.CharField(blank=True, max_length=50)),
                ('entrance', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('intercom', models.CharField(blank=True, max_length=50)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, help_text='For automated birthday discount campaigns.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff.')),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('accepts_sms', models.BooleanField(default=False)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('vip', 'VIP'), ('dormant', 'Dormant')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_spent'],
            },
        ),
        migrations.CreateModel(
            name='ShopInvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, help_text='Official company name (ООО "Название").', max_length=300)),
                ('inn', models.CharField(blank=True, help_text='ИНН — Russian tax number.', max_length=20)),
                ('kpp', models.CharField(blank=True, help_text='КПП', max_length=20)),
                ('ogrn', models.CharField(blank=True, help_text='ОГРН', max_length=20)),
                ('legal_address', models.CharField(blank=True, max_length=500)),
                ('bank_name', models.CharField(blank=True, max_length=300)),
                ('bank_bik', models.CharField(blank=True, help_text='БИК', max_length=20)),
                ('bank_account', models.CharField(blank=True, help_text='Р/С', max_length=30)),
                ('correspondent_account', models.CharField(blank=True, help_text='К/С', max_length=30)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='VAT %. Use 0 if shop is on USN (simplified tax).', max_digits=5)),
                ('vat_included_in_price', models.BooleanField(default=True)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_logo', models.ImageField(blank=True, null=True, upload_to='invoice-logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Shop invoice settings',
                'verbose_name_plural': 'Shop invoice settings',
            },
        ),
        migrations.CreateModel(
            name='ShopNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_email', models.EmailField(blank=True, help_text='Where alerts are sent. Defaults to shop email.', max_length=254)),
                ('notify_on_new_order', models.BooleanField(default=True)),
                ('notify_on_paid_order', models.BooleanField(default=True)),
                ('notify_on_low_stock', models.BooleanField(default=True)),
                ('notify_on_failed_payment', models.BooleanField(default=True)),
                ('telegram_bot_token', accounts.shop_settings.EncryptedTextField(blank=True, default='')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Shop notification settings',
                'verbose_name_plural': 'Shop notification settings',
            },
        ),
        migrations.CreateModel(
            name='ShopPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sberbank_enabled', models.BooleanField(default=False)),
                ('sberbank_mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=10)),
                ('sberbank_username', models.CharField(blank=True, max_length=200)),
                ('sberbank_password_encrypted', accounts.shop_settings.EncryptedTextField(blank=True, default='')),
                ('sberbank_token', accounts.shop_settings.EncryptedTextField(blank=True, default='', help_text='Optional API token if used instead of username/password.')),
                ('sberbank_return_url', models.URLField(blank=True)),
                ('sberbank_fail_url', models.URLField(blank=True)),
                ('cash_on_delivery_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Shop payment settings',
                'verbose_name_plural': 'Shop payment settings',
            },
        ),
    ]
