# Generated by Django 5.2.13 on 2026-05-02 18:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('restock', 'Restock'), ('adjustment', 'Manual adjustment'), ('return', 'Return'), ('waste', 'Waste/spoilage')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('stock_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.shop')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='flowers/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Alert manager when stock drops to or below this number.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('available_for_custom', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='catalog.category')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Discount applies when buying at least this many stems.', validators=[django.core.validators.MinValueValidator(1)])),
                ('percent', models.DecimalField(decimal_places=2, help_text='Percentage of base price to charge (e.g. 95 = 5% off).', max_digits=5)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_tiers', to='catalog.flower')),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='FlowerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of stems in this option.', validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(blank=True, help_text='Display name; if empty, generated from quantity.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.flower')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('badge_text', models.CharField(blank=True, help_text='Short label shown on cards, e.g. "−20%", "Хит", "Новинка".', max_length=50)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='If percent: 10 means 10% off. If fixed: 500 means 500 ₽ off.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('promo_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('scope', models.CharField(choices=[('all', 'All flowers'), ('categories', 'Selected categories'), ('flowers', 'Selected flowers')], default='all', max_length=20)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total before discount applies (0 = no minimum).', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total times this promo can be used across all customers. Blank = unlimited.', null=True)),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, help_text='Per-customer limit. Blank = unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page and Sales page hero.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Used when scope = "categories".', related_name='promotions', to='catalog.category')),
                ('flowers', models.ManyToManyField(blank=True, help_text='Used when scope = "flowers".', related_name='promotions', to='catalog.flower')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.shop')),
            ],
            options={
                'ordering': ['-is_featured', 'sort_order', '-starts_at'],
            },
        ),
    ]
