# Generated by Django 5.2.13 on 2026-05-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='catalog.promotion'),
        ),
        migrations.AddField(
            model_name='promotionusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.flower'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='flower',
            unique_together={('category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='discounttier',
            unique_together={('flower', 'min_quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='flowersize',
            unique_together={('flower', 'quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('shop', 'slug')},
        ),
    ]
